import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'pink',
    paddingTop: 40,
  },
  difficultyContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 20,
    gap: 10,
  },
  difficultyButton: {
    padding: 15,
    borderRadius: 25,
    width: '40%',
    alignItems: 'center',
  },
  timer: {
    fontSize: 32,
    textAlign: 'center',
    marginBottom: 20,
    color: 'white',
    fontWeight: 'bold',
  },
  text: {
    fontSize: 24,
    color: 'white',
    textAlign: 'center',
    marginBottom: 15,
    fontWeight: '600',
    border: '1px solid white',
  },
  numberContainer: {
    fontSize: 24,
    color: 'white',
    textAlign: 'center',
    lignItems: 'center',
    alignSelf: 'center',
    width: '50%',
    borderWidth: 2,
    borderColor: 'lemonchiffon', 
    borderRadius: 10, 
    padding: 10,
  },
  numberText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'pink',
  },
  input: {
    borderWidth: 2,
    borderColor: 'lemonchiffon',
    padding: 15,
    marginVertical: 20,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    width: '100%',
    fontSize: 20,
    textAlign: 'center',
    border: '1px solid white',
  },
  message: {
    margin: 10,
    textAlign: 'center',
    color: 'lemonchiffon',
    fontSize: 20,
    fontWeight: '600',
  },
  buttonContainer: {
    width: '100%',
    alignItems: 'center',
    gap: 15,
  },
  buttonText: {
    color: 'pink',
    textShadowColor: 'white',
    textShadowRadius: 4,
    fontSize: 20,
    fontWeight: 'bold',
  }
});